from datetime import date, datetime
from typing import Protocol
from ..schemas.domain import DailyBriefRead, OpportunityAction, OpportunityRead, PreferenceState, ProfileRead, ProfileUpsert, RadarCreate, RadarRead, RadarRunRead, RawItem
from ..schemas.intelligence import ChangeEventRead, EventClusterRead, PainPointRead, SignalRead, SourceHealthRead, TrendSnapshotRead, TrendTopicRead


class Repository(Protocol):
    """Persistence contract shared by MemoryRepository and PostgresRepository."""

    def get_profile(self, user_id: str) -> ProfileRead: ...
    def save_profile(self, user_id: str, value: ProfileUpsert) -> ProfileRead: ...
    def list_radars(self, user_id: str) -> list[RadarRead]: ...
    def get_radar(self, user_id: str, radar_id: str) -> RadarRead: ...
    def create_radar(self, user_id: str, value: RadarCreate) -> RadarRead: ...
    def save_radar(self, item: RadarRead) -> RadarRead: ...
    def delete_radar(self, user_id: str, radar_id: str) -> None: ...
    def has_raw(self, radar_id: str, url: str) -> bool: ...
    def mark_raw(self, radar_id: str, url: str, item: RawItem | None = None, embedding: list[float] | None = None) -> str: ...
    def find_similar_raw(self, radar_id: str, vector: list[float], threshold: float = 0.92) -> str | None:
        """Returns the id of a previously stored raw item whose embedding is
        cosine-similar above threshold, else None (cross-run semantic dedup)."""
        ...
    def create_run(self, radar_id: str) -> RadarRunRead: ...
    def save_run(self, run: RadarRunRead) -> RadarRunRead: ...
    def get_run(self, user_id: str, run_id: str) -> RadarRunRead: ...
    def runs_of_user(self, user_id: str) -> list[RadarRunRead]: ...
    def add_opportunity(self, item: OpportunityRead, user_id: str | None = None) -> OpportunityRead: ...
    def list_opportunities(self, user_id: str) -> list[OpportunityRead]: ...
    def get_opportunity(self, user_id: str, opportunity_id: str) -> OpportunityRead: ...
    def save_opportunity(self, item: OpportunityRead) -> OpportunityRead: ...
    def record_action(self, opportunity_id: str, payload: OpportunityAction, action: str | None = None) -> OpportunityAction: ...
    def scanned_count(self, user_id: str) -> int: ...
    def won_revenue(self, user_id: str) -> int: ...
    def daily_brief(self, user_id: str) -> DailyBriefRead: ...
    def list_due_radars(self, now: datetime) -> list[tuple[str, str]]: ...
    def record_llm_call(self, user_id: str | None, radar_id: str | None, run_id: str | None, provider: str | None, model: str, latency_ms: int, fallbacked: bool, schema_name: str, stage: str | None = None, input_count: int | None = None, output_count: int | None = None, prompt_tokens: int | None = None, completion_tokens: int | None = None, cost_usd: float | None = None) -> None: ...
    def get_preference(self, user_id: str) -> PreferenceState: ...
    def save_preference(self, user_id: str, state: PreferenceState) -> PreferenceState: ...
    def record_event(self, user_id: str, opportunity_id: str | None, event: str, metadata: dict | None = None) -> None: ...

    # ---- Money Intelligence extensions (Phase 1) ----
    def add_signal(self, signal: SignalRead, radar_id: str | None = None, raw_item_id: str | None = None, cluster_id: str | None = None) -> SignalRead: ...
    def list_signals(self, user_id: str, radar_id: str | None = None, limit: int = 100) -> list[SignalRead]: ...
    def save_cluster(self, cluster: EventClusterRead, radar_id: str | None = None, member_raw_item_ids: list[str] | None = None) -> EventClusterRead: ...
    def list_clusters(self, user_id: str, radar_id: str | None = None, limit: int = 50) -> list[EventClusterRead]: ...
    def upsert_trend_topic(self, topic: TrendTopicRead) -> TrendTopicRead: ...
    def save_trend_snapshot(self, snapshot: TrendSnapshotRead) -> TrendSnapshotRead: ...
    def list_trend_topics(self, user_id: str | None = None, radar_id: str | None = None, limit: int = 100) -> list[TrendTopicRead]: ...
    def list_trend_snapshots(self, topic_id: str, limit: int = 720) -> list[TrendSnapshotRead]: ...
    def save_change_event(self, event: ChangeEventRead, radar_id: str | None = None) -> ChangeEventRead: ...
    def list_change_events(self, user_id: str | None = None, radar_id: str | None = None, limit: int = 100) -> list[ChangeEventRead]: ...
    def record_source_health(self, slug: str, ok: bool, items: int, latency_ms: int, error_code: str | None = None, error_message: str | None = None) -> None: ...
    def get_source_health(self, slug: str) -> SourceHealthRead | None: ...
    def list_source_health(self) -> list[SourceHealthRead]: ...

    # ---- P1 guardrails / Phase 2 ----
    def get_brief(self, user_id: str, brief_date: date) -> DailyBriefRead | None: ...
    def cleanup_raw_items(self, days: int) -> int: ...
    def cleanup_llm_calls(self, days: int) -> int: ...
    def merge_cluster(self, source_id: str, target_id: str) -> None:
        """Reattach source's members to target, mark source merged_into target."""
        ...
    def upsert_pain_point(self, pain: PainPointRead) -> PainPointRead: ...
    def list_pain_points(self, user_id: str, radar_id: str | None = None, limit: int = 50) -> list[PainPointRead]: ...
    def list_radar_pairs(self) -> list[tuple[str, str]]:
        """All (user_id, radar_id) pairs — maintenance jobs iterate these."""
        ...
