from datetime import datetime
from typing import Protocol
from ..schemas.domain import DailyBriefRead, OpportunityAction, OpportunityRead, ProfileRead, ProfileUpsert, RadarCreate, RadarRead, RadarRunRead, RawItem


class Repository(Protocol):
    """Persistence contract shared by MemoryRepository and PostgresRepository."""

    def get_profile(self, user_id: str) -> ProfileRead: ...
    def save_profile(self, user_id: str, value: ProfileUpsert) -> ProfileRead: ...
    def list_radars(self, user_id: str) -> list[RadarRead]: ...
    def get_radar(self, user_id: str, radar_id: str) -> RadarRead: ...
    def create_radar(self, user_id: str, value: RadarCreate) -> RadarRead: ...
    def save_radar(self, item: RadarRead) -> RadarRead: ...
    def delete_radar(self, user_id: str, radar_id: str) -> None: ...
    def has_raw(self, radar_id: str, url: str) -> bool: ...
    def mark_raw(self, radar_id: str, url: str, item: RawItem | None = None) -> None: ...
    def create_run(self, radar_id: str) -> RadarRunRead: ...
    def save_run(self, run: RadarRunRead) -> RadarRunRead: ...
    def get_run(self, user_id: str, run_id: str) -> RadarRunRead: ...
    def runs_of_user(self, user_id: str) -> list[RadarRunRead]: ...
    def add_opportunity(self, item: OpportunityRead, user_id: str | None = None) -> OpportunityRead: ...
    def list_opportunities(self, user_id: str) -> list[OpportunityRead]: ...
    def get_opportunity(self, user_id: str, opportunity_id: str) -> OpportunityRead: ...
    def save_opportunity(self, item: OpportunityRead) -> OpportunityRead: ...
    def record_action(self, opportunity_id: str, payload: OpportunityAction, action: str | None = None) -> OpportunityAction: ...
    def scanned_count(self, user_id: str) -> int: ...
    def won_revenue(self, user_id: str) -> int: ...
    def daily_brief(self, user_id: str) -> DailyBriefRead: ...
    def list_due_radars(self, now: datetime) -> list[tuple[str, str]]: ...
    def record_llm_call(self, user_id: str | None, radar_id: str | None, run_id: str | None, provider: str | None, model: str, latency_ms: int, fallbacked: bool, schema_name: str) -> None: ...
