"use client";
import { Menu, Radar, Bell, Search } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { cn } from "@/lib/utils";
const nav = [["首页", "/dashboard"], ["机会列表", "/opportunities"], ["我的雷达", "/radars"], ["每日简报", "/daily-brief"], ["机会进度", "/pipeline"], ["已收藏", "/saved"], ["机会技能", "/skills"], ["我的画像", "/profile"], ["设置", "/settings"]] as const;
function Navigation({ onSelect }: { onSelect?: () => void }) { const path = usePathname(); return <nav className="space-y-1">{nav.map(([label, href]) => <Link key={href} onClick={onSelect} href={href} className={cn("block rounded px-3 py-2 text-sm transition", path === href || (href !== "/dashboard" && path.startsWith(href)) ? "border-l-2 border-ai bg-white/5 text-white" : "text-muted hover:bg-white/5 hover:text-mist")}>{label}</Link>)}</nav>; }
export function AppShell({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); return <div className="min-h-screen bg-ink"><aside className="fixed inset-y-0 left-0 z-30 hidden w-60 border-r border-line bg-[#061728] p-4 lg:block"><Link href="/dashboard" className="mb-8 flex items-center gap-2 text-sm font-semibold text-white"><span className="grid h-8 w-8 place-items-center rounded bg-ai shadow-glow"><Radar size={17}/></span><span>机会雷达 <small className="block font-normal text-muted">Opportunity Radar</small></span></Link><p className="mb-2 px-3 text-[11px] font-semibold tracking-widest text-muted">工作台</p><Navigation/><div className="absolute bottom-4 left-4 right-4 border-t border-line pt-4 text-xs text-muted">AI 每天替你发现机会</div></aside><header className="sticky top-0 z-20 flex h-14 items-center justify-between border-b border-line bg-ink/95 px-4 backdrop-blur lg:ml-60"><button aria-label="打开导航" className="lg:hidden" onClick={() => setOpen(true)}><Menu/></button><div className="hidden items-center gap-2 text-sm text-muted sm:flex"><Search size={16}/> 搜索你的机会</div><div className="flex items-center gap-4 text-muted"><Bell size={18}/><span className="grid h-8 w-8 place-items-center rounded-full bg-panel text-xs text-mist">小何</span></div></header>{open && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/60" aria-label="关闭导航" onClick={() => setOpen(false)}/><aside className="relative h-full w-72 border-r border-line bg-[#061728] p-5"><div className="mb-8 flex items-center gap-2 font-semibold"><Radar className="text-indigo-300"/>机会雷达</div><Navigation onSelect={() => setOpen(false)}/></aside></div>}<main className="min-h-[calc(100vh-56px)] p-4 sm:p-6 lg:ml-60 lg:p-8">{children}</main></div>; }
