"use client";
import { Bookmark, Check, ExternalLink, EyeOff, MessageSquare } from "lucide-react";
import Link from "next/link";
import { useOpportunityStore } from "@/stores/use-opportunity-store";
import type { Opportunity } from "@/types/domain";
import { yuan } from "@/lib/utils";
import { Button, Panel } from "@/components/ui";
const sourceLabel: Record<Opportunity["sourceType"], string> = { xiaohongshu: "小红书", boss: "BOSS直聘", github: "GitHub", reddit: "Reddit", web: "公开网页", forum: "论坛" };
export function OpportunityCard({ opportunity, compact = false }: { opportunity: Opportunity; compact?: boolean }) { const { toggleSaved, updateOpportunity } = useOpportunityStore(); const saved = opportunity.status === "saved"; return <Panel className="p-4 transition hover:border-slate-500"><div className="flex gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded border border-line px-2 py-1 text-muted">{sourceLabel[opportunity.sourceType]}</span><span className="mono text-muted">{opportunity.publishedAt}</span><span className="ml-auto rounded bg-indigo-400/15 px-2 py-1 font-medium text-indigo-200">匹配 {opportunity.matchScore}%</span></div><Link href={`/opportunities/${opportunity.id}`} className="mt-3 block text-base font-semibold text-mist hover:text-indigo-200">{opportunity.title}</Link>{!compact && <p className="mt-2 line-clamp-2 text-sm leading-6 text-muted">{opportunity.summary}</p>}<div className="mt-3 flex flex-wrap gap-2">{opportunity.skills.slice(0, compact ? 2 : 4).map((skill) => <span key={skill} className="rounded-full border border-line px-2 py-0.5 text-xs text-slate-300">{skill}</span>)}</div></div></div><div className="mt-4 grid grid-cols-2 gap-2 border-t border-line pt-3 text-xs sm:grid-cols-4"><span><b className="block text-mist">{yuan(opportunity.budgetMin)}–{yuan(opportunity.budgetMax)}</b>预算</span><span><b className="block text-mist">{opportunity.estimatedHours} 小时</b>预计耗时</span><span><b className="block text-signal">{opportunity.opportunityScore}</b>机会评分</span><span><b className="block text-amber-300">{opportunity.riskScore}</b>风险指数</span></div>{!compact && <div className="mt-4 flex flex-wrap gap-2"><Link href={`/opportunities/${opportunity.id}`}><Button variant="secondary"><Check size={14}/>查看分析</Button></Link><a href={opportunity.sourceUrl} target="_blank"><Button variant="ghost"><ExternalLink size={14}/>原帖</Button></a><Button variant="ghost" aria-label={saved ? "取消收藏" : "收藏"} onClick={() => toggleSaved(opportunity.id)}><Bookmark size={14} className={saved ? "fill-indigo-300 text-indigo-300" : ""}/>{saved ? "已收藏" : "收藏"}</Button><Button variant="ghost" onClick={() => updateOpportunity(opportunity.id, "contacted")}><MessageSquare size={14}/>已联系</Button><Button variant="ghost" onClick={() => updateOpportunity(opportunity.id, "ignored")}><EyeOff size={14}/>暂不考虑</Button></div>}</Panel>; }
