"use client";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { OpportunityCard } from "@/components/opportunity-card";
import { PageHeader } from "@/components/ui";
import { useOpportunityStore } from "@/stores/use-opportunity-store";
import type { OpportunityType } from "@/types/domain";
const typeMap: Record<string, OpportunityType | "all"> = { "全部": "all", "工作": "job", "客户": "client", "项目": "project", "商机": "business", "GitHub": "github" };
export default function OpportunitiesPage() { const [query, setQuery] = useState(""); const [type, setType] = useState<OpportunityType | "all">("all"); const [sort, setSort] = useState("推荐"); const items = useOpportunityStore((s) => s.opportunities); const filtered = useMemo(() => items.filter((x) => (type === "all" || (type === "github" ? x.sourceType === "github" : true)) && `${x.title}${x.summary}${x.skills.join("")}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "最新" ? b.publishedAt.localeCompare(a.publishedAt) : sort === "预算" ? b.budgetMax - a.budgetMax : sort === "风险" ? a.riskScore - b.riskScore : b.opportunityScore - a.opportunityScore), [items, query, sort, type]); return <AppShell><PageHeader title="机会列表" description="AI 根据你的能力、偏好和收入目标自动排序。"/><div className="space-y-3"><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full rounded border border-line bg-panel px-3 py-2 text-sm" placeholder="搜索机会" aria-label="搜索机会"/><div className="flex flex-wrap gap-2">{Object.entries(typeMap).map(([label, value]) => <button onClick={() => setType(value)} className={`rounded px-3 py-1.5 text-sm ${type === value ? "bg-ai text-white" : "border border-line text-muted"}`} key={label}>{label}</button>)}<select className="ml-auto rounded border border-line bg-panel px-2 text-sm" value={sort} onChange={(e) => setSort(e.target.value)} aria-label="排序"><option>AI 推荐</option><option>最新</option><option>预算</option><option>风险</option></select></div></div><div className="mt-5 space-y-3">{filtered.map((item) => <OpportunityCard key={item.id} opportunity={item}/>)}</div></AppShell>; }
