"use client";
import Link from "next/link";
import { ArrowRight, Radar } from "lucide-react";
import { mockBrief } from "@/data/mock-profile";
import { useOpportunityStore } from "@/stores/use-opportunity-store";
import { MetricCard, PageHeader, Panel } from "@/components/ui";
import { OpportunityCard } from "@/components/opportunity-card";
import { yuan } from "@/lib/utils";
export function Dashboard() { const opportunities = useOpportunityStore((s) => s.opportunities); const radars = useOpportunityStore((s) => s.radars); const active = opportunities.filter((x) => !["ignored", "lost"].includes(x.status)); const won = opportunities.filter((x) => x.status === "won"); return <><PageHeader title="晚上好 👋" description={`AI 今天为你发现了 ${active.length + 21} 个与你匹配的新机会`} action={<Link href="/radars/new" className="rounded bg-ai px-3 py-2 text-sm font-medium text-white">创建雷达</Link>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="今日扫描" value="12,481" hint="来自 6 个数据来源"/><MetricCard label="发现机会" value="137" hint="已去除重复内容"/><MetricCard label="与你匹配" value="26" tone="ai" hint="基于你的机会画像"/><MetricCard label="强烈推荐" value="8" tone="good" hint="建议今天优先行动"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-6"><Panel className="grid-bg overflow-hidden p-5"><p className="text-sm text-muted">今日潜在收入</p><p className="mono mt-2 text-3xl font-semibold text-signal">{yuan(mockBrief.potentialIncome[0])} – {yuan(mockBrief.potentialIncome[1])}</p><p className="mt-2 max-w-xl text-sm text-muted">根据今日推荐机会的预算、预计工作量与成交概率估算。</p></Panel><div><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">今日最值得关注</h2><Link className="flex items-center gap-1 text-sm text-indigo-200" href="/opportunities">查看全部 <ArrowRight size={14}/></Link></div><div className="space-y-3">{active.slice(0, 3).map((item) => <OpportunityCard key={item.id} opportunity={item}/>)}</div></div></div><aside className="space-y-6"><Panel className="p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">我的雷达</h2><Link href="/radars" className="text-sm text-indigo-200">管理</Link></div><div className="space-y-3">{radars.map((radar) => <Link href={`/radars/${radar.id}`} key={radar.id} className="block border-t border-line pt-3 first:border-0 first:pt-0"><div className="flex items-center justify-between"><span className="text-sm text-mist">{radar.name}</span><span className={radar.status === "running" ? "text-xs text-signal" : "text-xs text-muted"}>{radar.status === "running" ? "运行中" : "已暂停"}</span></div><p className="mono mt-1 text-xs text-muted">{radar.stats.matched} 个新机会 · {radar.lastRunAt}</p></Link>)}</div></Panel><Panel className="p-4"><h2 className="font-semibold">机会趋势</h2>{mockBrief.trends.map((trend) => <div key={trend} className="mt-3 flex gap-2 text-sm text-muted"><Radar size={16} className="shrink-0 text-indigo-300"/>{trend}</div>)}</Panel><Panel className="p-4"><p className="text-sm font-medium text-mist">本月已成交</p><p className="mono mt-2 text-2xl text-signal">{won.length} 笔</p><p className="mt-1 text-xs text-muted">继续保持高频跟进</p></Panel></aside></div></>; }
