"use client";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { OpportunityCard } from "@/components/opportunity-card";
import { MetricCard, PageHeader, Panel } from "@/components/ui";
import { getBrief } from "@/services/brief.service";
import { useOpportunityStore } from "@/stores/use-opportunity-store";
import type { DailyBrief } from "@/types/domain";
export default function DailyBrief(){const items=useOpportunityStore(s=>s.opportunities);const [brief,setBrief]=useState<DailyBrief|null>(null);const date=new Intl.DateTimeFormat("zh-CN",{dateStyle:"full"}).format(new Date());useEffect(()=>{void getBrief().then(setBrief).catch(()=>setBrief(null));},[]);return <AppShell><PageHeader title="每日机会简报" description={date}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["累计扫描",brief?.scanned??"—"],["发现机会",brief?.found??items.length],["强烈推荐",brief?.recommended??"—"],["潜在收入",brief?`¥${brief.potentialIncome[0]}–¥${brief.potentialIncome[1]}`:"—"]].map(([l,v])=><MetricCard key={String(l)} label={String(l)} value={String(v)}/>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_320px]"><div><h2 className="mb-3 font-semibold">今日最值得行动</h2><div className="space-y-3">{items.slice(0,3).map(x=><OpportunityCard key={x.id} opportunity={x}/>)}</div></div><div className="space-y-5"><Panel className="p-5"><h2 className="font-semibold">今日趋势</h2>{(brief?.trends??[]).map((x,i)=><p className="mt-3 text-sm text-muted" key={i}>{x}</p>)}</Panel><Panel className="p-5"><h2 className="font-semibold">今天不建议做</h2><p className="mt-3 text-sm text-amber-100">{brief?.avoid||"暂无建议。"}</p></Panel><Panel className="p-5"><h2 className="font-semibold">AI 建议你今天优先做</h2>{(brief?.actions??[]).map((x,i)=><p className="mt-3 text-sm" key={i}>{i+1}. {x}</p>)}</Panel></div></div></AppShell>}
